#!/home/qqbot/.conda/envs/webserver/bin/python3

import os,time

scode = os.getenv("SELF_CODE")
try:
    with open("/home/qqbot/axuanWEB/logs/gunicorn.pid","r") as f:
        f.seek(0)
        pid = f.readline().split("\n")[0]
    
    os.system(f"echo {scode} | sudo -S kill {pid}")
    time.sleep(2)
finally:
    os.chdir('/home/qqbot/axuanWEB')
    os.system(f"echo {scode} | sudo -S /home/qqbot/.conda/envs/webserver/bin/gunicorn start:app -c gunicorn_conf.py &")
